
name: criar release

on:
  push:
    branches:
      - staging

permissions:
  contents: write
  pull-requests: write

jobs:
  criar-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          default-branch: main
          token: ${{ secrets.GITHUB_TOKEN }}
          package-name: ci-cd-github-actions
  
  criar-nova-release-actions:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "release.tar.gz,foo/*.txt"