
name: criar release

on:
  push:
    branches:
      - staging

permissions:
  contents: write
  pull-requests: write

jobs:
  criar-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          default-branch: main
          token: ${{ secrets.GITHUB_TOKEN }}
          package-name: ci-cd-github-actions
  
  criar-nova-release-actions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: iamkubi/github-release@2.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: v0.0.1